services:
    frontend:
        build:
            context: ./luxuryproducts-frontend
        ports:
            - "4200:80"
        depends_on:
            - backend
            - postgres

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: webshopbob
            POSTGRES_USER:
            POSTGRES_PASSWORD:
        ports:
            - "5432:5432"

    backend:
        build:
            context: ./luxuryproducts-backend
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/webshopbob
            - SPRING_DATASOURCE_USERNAME=
            - SPRING_DATASOURCE_PASSWORD=
        depends_on:
            - postgres
