FROM node:22-alpine AS build

WORKDIR /app

RUN npm install -g @angular/cli

RUN npm cache clean --force

COPY . .

RUN npm install
RUN npm run build

FROM nginx:latest as nginx

COPY --from=build /app/dist/infirfs-auth-project/browser /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
